# Generated by Django 2.1 on 2018-08-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acname', models.CharField(max_length=20)),
                ('aename', models.CharField(max_length=50)),
                ('methodnum', models.IntegerField()),
                ('adescription', models.CharField(max_length=1000)),
                ('ainfolink', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mehtods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcname', models.CharField(max_length=20)),
                ('mename', models.CharField(max_length=50)),
                ('mdescription', models.CharField(max_length=1000)),
                ('minfolink', models.CharField(max_length=50)),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labapp.Area')),
            ],
        ),
    ]
