# Generated by Django 2.1 on 2018-08-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_auto_20180828_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=20)),
                ('linkhot', models.IntegerField(default=0)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labapp.Mehtods')),
            ],
        ),
    ]
